In [3]:
class Network:
    def __init__(self):
        self.layer = None
        
    def forward(self,t):
        t = self.layer(t)
        return t

In [81]:
import torch.nn as nn
import torch
import torch.nn.functional as F

In [102]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self,t):
        #(1) input Layer
        t = t
        
        #(2) hidden conv Layer
        t = self.conv1(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        #(3) hidden conv Layer
        t = self.conv2(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=1, stride=2)
        
        #(4) hidden Liner Layer
        t = t.reshape(-1,12*4*4)
        t = self.fc1(t)
        t = F.relu(t)
        
        #(5) hidden Linear Layer
        t = self.fc2(t)
        t = F.relu(t)
        
        #(6) output Layer
        t = self.out(t)
        #t = F.softmax(t, dim=1)
        
        return t
    
    #def __repr__(self):
        #return 'lizard'
        

In [103]:
net = Network()

In [104]:
print(net)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


In [105]:
net.conv1

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [106]:
net.conv1.weight

Parameter containing:
tensor([[[[-0.0912,  0.1695,  0.0870, -0.0886, -0.0487],
          [ 0.0836,  0.0677, -0.1510,  0.1357, -0.0255],
          [ 0.1638, -0.0670,  0.1655,  0.1970,  0.1355],
          [-0.0603,  0.0668,  0.1414, -0.1263,  0.0921],
          [ 0.0500, -0.1054, -0.0688, -0.0398,  0.1971]]],


        [[[ 0.1692,  0.1194,  0.0577, -0.1128,  0.1055],
          [-0.0900,  0.0189,  0.1685, -0.1791, -0.1895],
          [ 0.0189, -0.0311,  0.1109, -0.0235, -0.0562],
          [ 0.0219,  0.0868, -0.1649,  0.0163, -0.0597],
          [-0.0076, -0.1936,  0.0853, -0.1140, -0.0828]]],


        [[[ 0.1813,  0.1989, -0.1068,  0.1298, -0.1705],
          [-0.0487,  0.1823,  0.0944, -0.0092,  0.0402],
          [ 0.0426,  0.0956,  0.1956,  0.0951,  0.0570],
          [-0.0189, -0.0282,  0.1926, -0.0438, -0.0647],
          [ 0.1959, -0.0204, -0.1292, -0.0929, -0.1828]]],


        [[[ 0.1810,  0.0549, -0.0769,  0.1013, -0.0835],
          [-0.1462, -0.1755, -0.1257, -0.1911,  0.1323

In [107]:
net.conv2.weight.shape

torch.Size([12, 6, 5, 5])

In [108]:
net.fc1.weight.shape

torch.Size([120, 192])

In [109]:
for param in net.parameters():
    print(param.shape)

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


In [110]:
for name,param in net.named_parameters():
    print(name,'\t\t',param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])


In [111]:
in_features = torch.tensor([1,2,3,4], dtype=torch.float32)

In [112]:
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
], dtype=torch.float32)

In [113]:
in_features_ano = torch.tensor([
    [1],
    [2],
    [3],
    [4]
], dtype=torch.float32)

In [114]:
in_features

tensor([1., 2., 3., 4.])

In [115]:
in_features_ano.T

tensor([[1., 2., 3., 4.]])

In [116]:
weight_matrix.T

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])

In [117]:
weight_matrix.matmul(in_features)

tensor([30., 40., 50.])

In [118]:
fc = nn.Linear(in_features=4, out_features=3, bias=False)

In [119]:
fc(in_features)

tensor([-0.9152, -3.5166, -3.0766], grad_fn=<SqueezeBackward3>)

In [120]:
fc.weight = nn.Parameter(weight_matrix)

In [121]:
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)