In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
import torchvision.transforms as transforms

torch.set_printoptions(linewidth=120)

In [2]:
train_set = torchvision.datasets.FashionMNIST(
    root='./data/FashionMINST'
    ,train=True
    ,download=True
    ,transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

In [6]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self, t):
        #(1) input Layer
        t = t
        
        #(2) hidden conv Layer
        t = self.conv1(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        #(3) hidden conv Layer
        t = self.conv2(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=1, stride=2)
        
        #(4) hidden Liner Layer
        t = t.reshape(-1,12*4*4)
        t = self.fc1(t)
        t = F.relu(t)
        
        #(5) hidden Linear Layer
        t = self.fc2(t)
        t = F.relu(t)
        
        #(6) output Layer
        t = self.out(t)
        #t = F.softmax(t, dim=1)
        
        return t

In [7]:
torch.set_grad_enabled(False)

In [21]:
net = Network()

In [22]:
sample = next(iter(train_set))

In [23]:
image, label = sample

In [24]:
image.shape

torch.Size([1, 28, 28])

In [25]:
image = image.unsqueeze(0)

In [26]:
pred = net(image)

In [27]:
pred.shape

torch.Size([1, 10])

In [30]:
pred

tensor([[ 0.0430, -0.0892, -0.0249, -0.0091,  0.0789,  0.1291, -0.0955, -0.0540, -0.0801, -0.0201]])

In [28]:
label

9

In [29]:
pred.argmax(dim=1)

tensor([5])

In [31]:
F.softmax(pred, dim=1)

tensor([[0.1054, 0.0924, 0.0985, 0.1001, 0.1093, 0.1149, 0.0918, 0.0957, 0.0932, 0.0990]])

In [32]:
F.softmax(pred, dim=1).sum()

tensor(1.)